name: flutter_fic_frontend
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0

  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  google_fonts: 6.1.0  
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.6  
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter  
  
flutter:    
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/menu/
    - assets/images/products/
    - assets/icons/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
